// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PortifolioDocumentDataSlicesSlice = never;

/**
 * Content for Portifolio documents
 */
interface PortifolioDocumentData {
  /**
   * Titulo field in *Portifolio*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: portifolio.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Post field in *Portifolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portifolio.post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  post: prismic.RichTextField;

  /**
   * Link do projeto field in *Portifolio*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portifolio.project_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField;

  /**
   * Slice Zone field in *Portifolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portifolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortifolioDocumentDataSlicesSlice> /**
   * Meta Description field in *Portifolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portifolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portifolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portifolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Portifolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portifolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Portifolio document from Prismic
 *
 * - **API ID**: `portifolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortifolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortifolioDocumentData>,
    "portifolio",
    Lang
  >;

export type AllDocumentTypes = PortifolioDocument;

/**
 * Default variation for Teste Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TesteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Teste*
 */
type TesteSliceVariation = TesteSliceDefault;

/**
 * Teste Shared Slice
 *
 * - **API ID**: `teste`
 * - **Description**: Teste
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TesteSlice = prismic.SharedSlice<"teste", TesteSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PortifolioDocument,
      PortifolioDocumentData,
      PortifolioDocumentDataSlicesSlice,
      AllDocumentTypes,
      TesteSlice,
      TesteSliceVariation,
      TesteSliceDefault,
    };
  }
}
